.github/workflows/golangci-lint.yaml
cmd/sentry.go
go.mod
go.sum
pkg/sentry/ethereum/metadata.go
pkg/sentry/ethereum/networks/network.go
pkg/sentry/ethereum/networks/network_test.go
pkg/sentry/sentry.go

Derives the network by using a hardcoded map of `slot -> block_root`. This obviously doesn't scale to testnets (those networks will be considered `unknown`), but it significantly improves the reliability of the network name. Previous we were using `spec.CONFIG_NAME`, but some clients don't provide this value, and others have inconsistent naming (i.e. Goerli/Prater is the same network with 2 configs now that they've merged).

feat(sentry): Derive network dynamically

---

pkg/mimicry/p2p/execution/event_transaction.go
pkg/mimicry/p2p/execution/execution.go

- actually get the full raw transaction data (not just call data)
- add a 15 second buffer from the start of connecting to a peer to not get the peers transaction pool old/stale txs

feat(mimicry): cleanup transactions event

---

pkg/server/server.go

Classic grpc load balancing problem for dns resolution
https://github.com/grpc/grpc/issues/12295#issuecomment-382794204
```
type ServerParameters struct {
// MaxConnectionIdle is a duration for the amount of time after which an
// idle connection would be closed by sending a GoAway. Idleness duration is
// defined since the most recent time the number of outstanding RPCs became
// zero or the connection establishment.
MaxConnectionIdle time.Duration // The current default value is infinity.
// MaxConnectionAge is a duration for the maximum amount of time a
// connection may exist before it will be closed by sending a GoAway. A
// random jitter of +/-10% will be added to MaxConnectionAge to spread out
// connection storms.
MaxConnectionAge time.Duration // The current default value is …
```

feat(server): set grpc MaxConnectionAge for dns connection cycling

---

.gitignore
pkg/server/geoip/maxmind/database/city.go
pkg/server/geoip/maxmind/maxmind.go

Fix incorrect usage of `RegisteredCountry` over `Country` field https://dev.maxmind.com/geoip/whats-new-in-geoip2?lang=en#country-registered-country-and-represented-country

fix(server): maxmind geoip country

---

pkg/proto/xatu/filter.go
pkg/proto/xatu/filter_test.go

Adds an `EventFilter` interface, which can be used by our `outputs` to filter out events they don't care about.

Add NewEventFilter and related tests for event filtering

---

pkg/proto/xatu/filter.go
pkg/proto/xatu/filter_test.go

Backported from https://github.com/ethpandaops/xatu/pull/108
Removes the `EventFilter.Apply()` method to simplify error handling when filtering multiple events, forcing the user of the filter to decide for themselves.

feat(proto): Remove EventFilter.Apply() method

---

pkg/sentry/ethereum/services/duties.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfa8daa]
goroutine 55 [running]:
github.com/ethpandaops/ethwallclock.(*EthereumBeaconChain).OnEpochChanged(...)
/home/runner/go/pkg/mod/github.com/ethpandaops/ethwallclock@v0.3.0/beacon_chain.go:92
github.com/ethpandaops/xatu/pkg/sentry/ethereum/services.(*DutiesService).Start(0xc000431960, {0x1775fe8?, 0xc000050018})
/home/runner/work/xatu/xatu/pkg/sentry/ethereum/services/duties.go:78 +0x12a
github.com/ethpandaops/xatu/pkg/sentry/ethereum.(*BeaconNode).Start.func1()
/home/runner/work/xatu/xatu/pkg/sentry/ethereum/beacon.go:77 +0x323
created by github.com/ethpandaops/xatu/pkg/sentry/ethereum.(*BeaconNode).Start …
```

fix(sentry): Panic fix in wallclock

---

pkg/server/service/coordinator/client.go
pkg/server/service/event-ingester/handler.go
pkg/server/service/event-ingester/ingester.go

Also errors out if any of the errors that were received were not valid

fix(server): Return correct GRPC errors

---

pkg/cannon/iterator/checkpoint_iterator.go

Doing this to reduce contention, will need a more well-thought-out solution longer term.

refactor(cannon): Lookahead 1 epoch

---

pkg/cannon/iterator/checkpoint_iterator.go

Fixes an issue where the slot default for a cannon type is greater than the finalized epoch. For example, Holesky starts Withdrawals/BLS changes at epoch 256, but epoch 256 hasn't been hit yet.

fix(cannon): Prevent checkpoint iterators going beyond head of chain

---

pkg/processor/batch.go

This isn't needed since the items are contained within this function

fix(processor): Drop mutex for ImmediatelyExportItems

---

pkg/sentry/ethereum/services/duties.go
pkg/sentry/ethereum/services/metadata.go

Forcefully refreshes the "required" tier of beacon duties any time:
- a reorg happens
- the sync status of the beacon node changes
- a new epoch starts.

fix(sentry): Beacon commitee duties cache overriding

---

pkg/cannon/cannon.go
pkg/cannon/deriver/beacon/eth/v1/beacon_blob.go
pkg/cannon/deriver/beacon/eth/v1/proposer_duty.go
pkg/cannon/deriver/beacon/eth/v2/attester_slashing.go
pkg/cannon/deriver/beacon/eth/v2/beacon_block.go
pkg/cannon/deriver/beacon/eth/v2/bls_to_execution_change.go
pkg/cannon/deriver/beacon/eth/v2/deposit.go
pkg/cannon/deriver/beacon/eth/v2/elaborated_attestation.go
pkg/cannon/deriver/beacon/eth/v2/execution_transaction.go
pkg/cannon/deriver/beacon/eth/v2/proposer_slashing.go
pkg/cannon/deriver/beacon/eth/v2/voluntary_exit.go
pkg/cannon/deriver/beacon/eth/v2/withdrawal.go
pkg/cannon/deriver/blockprint/block_classification.go
pkg/cannon/deriver/event_deriver.go
pkg/cannon/ethereum/forks.go

This allows us to just enable derivers ahead of forks and reduces the amount of mental load required when preparing for a fork

feat(cannon): Wait for forks to activate per deriver

---

.goreleaser.yaml
cmd/version.go
pkg/proto/xatu/xatu.go

```
./xatu version
xatu version 0.0.3-version 58cedcb linux/amd64
```

feat(cmd/version): add version command

---

go.mod
go.sum
pkg/sentry/ethereum/beacon.go
pkg/sentry/ethereum/services/metadata.go

Revert "feat(sentry): Improve startup procedure"

---

.golangci.yml

- `govet.check-shadowing` has been deprecated, in favour of [`enable.shadow`](https://golangci-lint.run/usage/linters/#govet). 
- `exportloopref` is a non-problem in Go 1.22 ([See docs](https://go.dev/blog/loopvar-preview)), adds [`copyloopvar`](https://golangci-lint.run/usage/linters/#copyloopvar) instead.

build(lint): update deprecated cfg + replace exportloopref w/ copyloopvar

---

deploy/migrations/clickhouse/053_validator_block.up.sql

Ensure clickhouse doesn't squash records by slot.

fix(xatu): updates orderby in migration for validator block

---

pkg/mimicry/p2p/execution/event_transaction.go
pkg/mimicry/p2p/execution/execution.go
pkg/processor/batch.go
pkg/processor/batch_test.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c796c1]
goroutine 11986827 [running]:
github.com/ethpandaops/xatu/pkg/processor.(*BatchItemProcessor[...]).exportWithTimeout(0x2d54940, {0x2d22720, 0x43ecfe0}, {0xc006974000, 0xc350, 0x0})
/workspace/pkg/processor/batch.go:289 +0x4a1
github.com/ethpandaops/xatu/pkg/processor.(*BatchItemProcessor[...]).worker(0x2d54940, {0x2d22720, 0x43ecfe0}, 0x2)
/workspace/pkg/processor/batch.go:468 +0x154
github.com/ethpandaops/xatu/pkg/processor.(*BatchItemProcessor[...]).Start.func1()
/workspace/pkg/processor/batch.go:200 +0x6c
created by github.com/ethpandaops/xatu/pkg/processor.(*BatchItemProcessor[...]).Start in goroutine 11857871 …

fix(processor): Fix panic from nil items

---

cmd/cannon.go
cmd/cl-mimicry.go
cmd/discovery.go
cmd/mimicry.go
cmd/relay-monitor.go
cmd/root.go
cmd/sentry.go
cmd/server.go
pkg/cannon/config.go
pkg/cannon/overrides.go
pkg/clmimicry/config.go
pkg/clmimicry/mimicry.go
pkg/clmimicry/overrides.go
pkg/discovery/config.go
pkg/discovery/discovery.go
pkg/discovery/overrides.go
pkg/mimicry/config.go
pkg/mimicry/mimicry.go
pkg/mimicry/overrides.go
pkg/relaymonitor/config.go
pkg/relaymonitor/overrides.go
pkg/relaymonitor/relay_monitor.go
pkg/sentry/overrides.go
pkg/sentry/sentry.go
pkg/server/config.go
pkg/server/overrides.go

Allows setting `--metrics-addr=:XXXX` via cli flag for the following Xatu pkgs...
- `cannon`
- `cl-mimicry`
- `discovery`
- `mimicry`
- `relay-monitor`
- `sentry`
- `server`
Takes precedence over any `metricsAddr` set in config.
<details>
<summary>Example (without flag)</summary>
```bash
go run main.go sentry                                                                                                                                                            
...
INFO[0000] Serving metrics at :9090                      module=sentry
```
</details>
<details>
<summary>Example (with flag)</summary>
```bash
go run main.go sentry --metrics-addr=:8765 …
```

refactor(xatu): allow setting metrics addr via cli flag

---

pkg/observability/tracing.go

**Fixes:** 
```
INFO[0000] Logger initialized                            fields.level=debug
...
INFO[0000] Tracing enabled                               module=sentry
FATA[0000] failed to create tracing resource: conflicting Schema URL: https://opentelemetry.io/schemas/1.26.0 and https://opentelemetry.io/schemas/1.24.0
exit status 1
```
Otel deps where bumped as part of https://github.com/ethpandaops/xatu/pull/410

fix(observability): bump otel schema

---

pkg/processor/batch.go

In an attempt to resolve `nil` items being run through the batch processor...
```
WARN[0250] Attempted to build a batch with a nil item. This item has been dropped. This probably shouldn't happen and is likely a bug.  node_record="enode://xx@xx:xx"
```
... this PR:
- Refactors channel closure in the batch builder to handle shutdown gracefully
- Improve queue draining sequence to prevent race conditions during shutdown
- Wait for in-flight batches to complete before closing channels

refactor(processor): improve batch processor shutdown and channel handling

---

pkg/server/server.go

> Ensure that the server's MaxConnectionAge exceeds NGINX's grpc_read_timeout and grpc_send_timeout to prevent NGINX from terminating connections before the server's age limit is reached.

refactor: Update MaxConnectionAge and MaxConnectionAgeGrace values

---

pkg/output/kafka/config.go
pkg/output/kafka/kafka.go

Introduce some kafka output options for batch processor, that are used in other output types

chore(kafka): batch processor config

---

.github/workflows/alpha-releases.yaml
.github/workflows/cannon-smoke-test.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/goreleaser.yaml
.github/workflows/sentry-smoke-test.yaml
.github/workflows/test-build.yaml
.github/workflows/test.yaml

- actions/checkout@v3 -> actions/checkout@v4
- actions/setup-go@v4 -> actions/setup-go@v5
- actions/setup-node@v3 -> actions/setup-node@v4
- docker/setup-qemu-action@v2 -> docker/setup-qemu-action@v3
- docker/setup-buildx-action@v2 -> docker/setup-buildx-action@v3
- docker/login-action@v2 -> docker/login-action@v3
Closes: https://github.com/ethpandaops/xatu/pull/389, https://github.com/ethpandaops/xatu/pull/361, https://github.com/ethpandaops/xatu/pull/263, https://github.com/ethpandaops/xatu/pull/249, https://github.com/ethpandaops/xatu/pull/233, https://github.com/ethpandaops/xatu/pull/232, https://github.com/ethpandaops/xatu/pull/231, https://github.com/ethpandaops/xatu/pull/230

ci(actions): bumps multiple actions versions

---

.gitignore
go.mod
go.sum
pkg/cannon/deriver/beacon/eth/v1/beacon_blob.go
pkg/cannon/deriver/beacon/eth/v1/beacon_committee.go
pkg/cannon/deriver/beacon/eth/v1/beacon_validators.go
pkg/cannon/deriver/beacon/eth/v1/proposer_duty.go
pkg/cannon/deriver/beacon/eth/v2/attester_slashing.go
pkg/cannon/deriver/beacon/eth/v2/beacon_block.go
pkg/cannon/deriver/beacon/eth/v2/bls_to_execution_change.go
pkg/cannon/deriver/beacon/eth/v2/deposit.go
pkg/cannon/deriver/beacon/eth/v2/elaborated_attestation.go
pkg/cannon/deriver/beacon/eth/v2/execution_transaction.go
pkg/cannon/deriver/beacon/eth/v2/proposer_slashing.go
pkg/cannon/deriver/beacon/eth/v2/voluntary_exit.go
pkg/cannon/deriver/beacon/eth/v2/withdrawal.go
pkg/cannon/deriver/blockprint/block_classification.go
pkg/cannon/ethereum/services/duties.go
pkg/cannon/ethereum/services/metadata.go
pkg/clmimicry/ethereum/services/duties.go
pkg/clmimicry/ethereum/services/metadata.go
pkg/sentry/ethereum/services/duties.go
pkg/sentry/ethereum/services/metadata.go

Bumps `cenkalti/backoff/v4` to `cenkalti/backoff/v5`.
- `RetryNotify` was removed, in favor of a single `Retry` method.
- `Retry` now takes `ctx`.
- Operation, now returns a result of `any` type.
See full change-log: https://github.com/cenkalti/backoff/blob/v5/CHANGELOG.md
Closes: https://github.com/ethpandaops/xatu/pull/432

refactor(xatu): bumps cenkalti/backoff to v5

---

.github/workflows/alpha-releases.yaml
.github/workflows/cannon-smoke-test.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/goreleaser.yaml
.github/workflows/sentry-smoke-test.yaml
.github/workflows/test-build.yaml
.github/workflows/test.yaml

This PR updates GitHub Actions to use pinned commit hashes for better security.

Update GitHub Actions to use pinned hashes

---

pkg/cannon/ethereum/services/client.go
pkg/ethereum/client.go
pkg/sentry/ethereum/services/client.go

See: https://github.com/ethpandaops/ethPandaOps/issues/1350
Adds support for `grandine` to xatu.

feat: Add ClientGrandine to Ethereum clients

---

example-cl-mimicry.yaml
go.mod
go.sum
pkg/clmimicry/config.go
pkg/clmimicry/mimicry.go

This commit introduces the ability to configure gossipsub subnets within the clmimicry application. This allows for more granular control over the pubsub network and enables the creation of specialized subnets for different types of data.
The following changes were made:
- Added a `Subnets` field to the `NodeConfig` struct in `pkg/clmimicry/config.go` to store the subnet configurations.
- Passed the `SubnetConfigs` to the hermes config in `pkg/clmimicry/config.go`.
- Updated the `AsHermesConfig` method in `pkg/clmimicry/config.go` to include the subnet configurations when creating the Hermes node configuration.
- Fixed a logging error in `pkg/clmimicry/mimicry.go`.
Depends on https://github.com/probe-lab/hermes/pull/51

feat(clmimicry): add gossipsub subnet configuration

---

pkg/cannon/ethereum/services/client.go
pkg/ethereum/client.go
pkg/sentry/ethereum/services/client.go

This commit introduces support for the Caplin Ethereum client. The changes include:
- Adding `ClientCaplin` constant to the `Client` enum in `pkg/cannon/ethereum/services/client.go`, `pkg/ethereum/client.go`, and `pkg/sentry/ethereum/services/client.go`.
- Adding `ClientCaplin` to the `AllClients` array in the same files.
- Updating the `ClientFromString` function to recognize "caplin" as a valid client string and return `ClientCaplin`.
These changes allow the system to correctly identify and interact with Ethereum nodes running the Caplin client.

feat: add Caplin client to supported Ethereum clients

---

example-cl-mimicry.yaml
go.mod
go.sum
pkg/clmimicry/config.go

The hermes library was replaced to use the ethpandaops fork.

fix(go.mod, go.sum): replace github.com/probe-lab/hermes with github.com/ethpandaops/hermes

---

pkg/clmimicry/mimicry.go

This commit adds support for TLS when connecting to the Prysm beacon node. The code now checks the `PrysmUseTLS` configuration option and prefixes the address with "https://" if it is enabled. This allows the mimicry service to securely connect to Prysm nodes that require TLS.

feat(mimicry.go): add TLS support for Prysm connection

---

.goreleaser.yaml

This change removes the go generate command from the goreleaser configuration. This is because go generate is not needed for the release process and can be run separately.

build(.goreleaser.yaml): remove go generate from goreleaser config

---

pkg/sentry/sentry.go

The sentry should be able to start even if the execution node is unavailable. This change allows the sentry to start without the mempool watcher, logging an error instead of returning an error. This prevents the sentry from failing to start when the execution node is unavailable.

fix(sentry): allow sentry to start without mempool watcher

---

go.mod
go.sum

Update the hermes dependency in go.mod and go.sum to incorporate recent changes now https://github.com/probe-lab/hermes/pull/56 has been merged. Continues using our fork to avoid funding.json capitalization issues.

build: update hermes dependency to a newer commit

---

pkg/sentry/execution/mempool_watcher.go
pkg/sentry/execution/mempool_watcher_test.go
pkg/sentry/execution/types.go

This commit introduces two new configuration flags, `EthPendingTxsEnabled` and `TxPoolContentEnabled`, to the `MempoolWatcher` configuration. These flags control whether the periodic fetching of `eth_pendingTransactions` and `txpool_content` is enabled, respectively.
Previously, both fetchers were always started when the `MempoolWatcher` was started. This change allows for more granular control over which methods are used to fetch pending transactions, enabling users to disable specific fetchers if they are not needed or causing issues.
A new test case `TestFetchersBasedOnConfig` has been added to verify that the fetcher goroutines are started or not based on the values of these configuration flags.

feat(mempool_watcher): add configuration flags to enable/disable fetchers

---

pkg/clmimicry/trace_shard_key.go
pkg/clmimicry/trace_shard_key_test.go

This change adds support for extracting the MsgID from payloads that are of type `map[string]any`. This is necessary because some message types, such as `deliver_message` and `duplicate_message`, use this format for their payload.
A new test case `TestGetMsgID` is also added to cover various scenarios, including map payloads with and without the MsgID field, and with different types for the MsgID value.

fix(clmimicry): handle map[string]any payloads in getMsgID

---

Makefile

The introduction of `llm` docs throughout the repo has caused issues with proto generation, mainly around the use of symlinks. `buf` fails to follow symlinks and when traversing the project generating, it fails with...
`Failure: EvalSymlinks: too many links`
This PR updates the `Makefile` to traverse the `pkg/proto` directories only, and use the explicit `--path` parameter of `buf` which gets us around it.
---
```bash
make proto                   
Buf generate:
-----------------
→ pkg/proto
→ pkg/proto/blockprint
→ pkg/proto/mevrelay
→ pkg/proto/eth
→ pkg/proto/eth/v1
→ pkg/proto/eth/v2
→ pkg/proto/xatu
→ pkg/proto/libp2p
→ pkg/proto/libp2p/gossipsub
-----------------
```

refactor(Makefile): improve proto generation script to iterate over dirs

---

pkg/clmimicry/mimicry.go

The previous implementation was adding metrics for the entire slice of events, not for each individual event within the slice. This change iterates over the slice and adds metrics for each event.

fix(clmimicry): iterate over events slice to add metrics for each event

---

pkg/clmimicry/event_libp2p.go
pkg/clmimicry/event_libp2p_test.go

The root level RPC events (SendRPC, RecvRPC, DropRPC) previously included the full RPC meta data payload. This payload can be very large, especially when containing many control messages, subscriptions, or messages. This can cause issues with message size limits downstream.
Since all detailed meta data is already being exploded into separate, individual events (e.g., RpcMetaControlIHave, RpcMetaSubscription, RpcMetaMessage), the full meta data is redundant in the root event.
This change modifies the root RPC event handlers to strip the large meta data fields (Control, Subscriptions, Messages) from the `Data` field of the root `DecoratedEvent`. The `Meta` field within the root event's data is also reduced to only include the `PeerId`.

refactor(clmimicry): strip large meta data from root RPC events

---

docker-compose.yml

Confluent Platform 7.9 is the last version supporting ZooKeeper - so our existing compose setup using `confluentinc/cp-kafka:latest` is failing. 
This PR migrates the local Docker Compose setup from ZooKeeper-based Kafka to KRaft mode, eliminating ZooKeeper dependency for Kafka.
We now have:
1. xatu-kafka-storage-format → formats KRaft storage directory
2. xatu-kafka → starts Kafka broker (depends on storage format)
3. xatu-init-kafka → creates topics (depends on Kafka healthy)

feat(docker-compose): migrate Kafka setup from Zookeeper to Kraft mode

---

docker-compose.yml

Bug with Vector `0.33.1` through `0.35.0`, occuring under high activity loads causing Vector to crash and restart in a loop.
See:  https://github.com/vectordotdev/vector/issues/19627
> It looks like `xatu-vector-kafka-clickhouse` and `xatu-vector-kafka-clickhouse-libp2p` were already on `0.37.1`, we were missing `xatu-vector-http-kafka`
```bash
thread 'vector-worker' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/registry/src/index.crates.io-6f17d22bba15001f/lockfree-object-pool-0.1.4/src/linear_page.rs:48:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-06-18T03:00:13.906700Z ERROR sink{component_kind="sink" component_id=libp2p_trace_send_rpc_kafka component_type=kafka}: vector::topology: An error occurred that Vector couldn't …
```

build(docker-compose.yml): update vector image version from 0.34.1-alpine to 0.37.1-alpine

---

pkg/clmimicry/event_libp2p.go
pkg/clmimicry/event_libp2p_test.go

The `parseRPCMetaControlPrune` function was updated to correctly handle PRUNE messages that do not contain peer IDs. Previously, it would skip processing if the `PeerIds` slice was empty. Now, it creates a single event with an empty `GraftPeerId` when no peer IDs are present, ensuring that all PRUNE activity is captured for network analysis, even when GossipSub PX is not enabled or used.

feat(clmimicry): handle PRUNE messages without peer IDs in *_RPC events

---

pkg/clmimicry/metrics.go

The metric name was plural, which is not consistent with the naming convention for Prometheus metrics. This change renames the metric to be singular.

refactor(clmimicry): rename decorated_events_total metric to decorated_event_total

---

example-cl-mimicry.yaml
pkg/clmimicry/sharding.go
pkg/clmimicry/sharding_test.go
pkg/clmimicry/trace_shard_key.go
pkg/clmimicry/trace_shard_key_test.go

This change introduces the ability to specify an event type constraint for sharding patterns. Previously, sharding patterns only matched against the topic string. This meant that a single pattern applied to all event types that had a matching topic.
With this change, a pattern can now be prefixed with an event type name followed by a colon (e.g., `LIBP2P_TRACE_GOSSIPSUB_BEACON_ATTESTATION:.*beacon_attestation.*`). This allows for more granular control over which events a specific sharding configuration applies to.
The `findTopicConfig` function has been updated to consider both the topic pattern and the event type constraint when determining the best matching configuration. Wildcard matching for event types (e.g., `LIBP2P_TRACE_RPC_META_*`) is also supported.
Backward compatibility is …

feat(clmimicry): add event type constraint to sharding patterns

---

pkg/clmimicry/event_libp2p_test.go

This commit introduces new test cases for various libp2p event types, including `ADD_PEER`, `REMOVE_PEER`, `JOIN`, `LEAVE`, `GRAFT`, `PRUNE`, `PUBLISH_MESSAGE`, `REJECT_MESSAGE`, `DELIVER_MESSAGE`, `DUPLICATE_MESSAGE`, `SEND_RPC`, and `DROP_RPC`.
The tests cover:
- Basic event handling and correct protobuf field population.
- Cases where events are disabled by configuration.
- Handling of invalid or missing payload data, expecting errors.
- Validation of multiple sub-events generated from a single trace event (e.g., RPC events with multiple messages or control messages).
- Edge cases like empty control messages or subscriptions.
These tests ensure the robustness and correctness of the event processing logic within the `clmimicry` package, particularly for the `handleHermesLibp2pEvent` and …

test(clmimicry): add comprehensive tests for libp2p event handlers

---

go.mod
go.sum
pkg/discovery/p2p/consensus_crawler.go
pkg/discovery/p2p/status.go

The `ethcore` crawler has its own retry logic built it, we don't need retry logic here now, let the crawler handle it.

feat(discovery): remove retry logic for consensus record addition

---

pkg/proto/xatu/coordinator.pb.go
pkg/proto/xatu/coordinator.proto
pkg/proto/xatu/coordinator_grpc.pb.go
pkg/server/persistence/integration_test.go
pkg/server/persistence/node_record_consensus.go
pkg/server/service/coordinator/client.go

- Introduce `BulkInsertNodeRecordConsensus` to insert many consensus records in a single transaction, batching 500-row chunks to stay within PostgreSQL parameter limits. Includes integration tests that verify correct insertion, empty-slice handling, foreign-key violations, and 600-row batching.
- Add `CreateConsensusNodeRecordStatuses` endpoint that accepts a list of consensus statuses, bulk-inserts the corresponding consensus records via `BulkInsertNodeRecordConsensus`, and updates the parent node records.

feat(coordinator.proto): add CreateConsensusNodeRecordStatuses RPC for bulk status creation

---

pkg/clmimicry/event_libp2p.go
pkg/clmimicry/event_libp2p_decoupled_test.go
pkg/clmimicry/event_libp2p_test.go

- Fixes issue where child events (like IHAVE) derived from SendRPC/RecvRPC were not captured when parent events were disabled or sharded out
- Allows child events to be captured at their configured sampling rate (e.g. 1% for IHAVE) even when parent RPC events are completely disabled

feat(cl-mimicry): decouple parent/child event sharding

---

cmd/relay-monitor.go
pkg/relaymonitor/config.go
pkg/relaymonitor/consistency.go
pkg/relaymonitor/iterator/forward_fill_iterator.go

Adds a `lag` configuration to the ForwardFill relay monitor configuration to let relays "settle" before we scrape them

feat(relaymonitor): add forward fill configuration and logic

---

deploy/migrations/clickhouse/071_data_column_sidecar.up.sql

- Add updated_date_time column for record versioning
- Switch to ReplicatedReplacingMergeTree engine for deduplication
- Add descriptive comments to all columns and table
- Include column_index in ORDER BY clause for better query performance
- Use cityHash64 for distributed table sharding instead of rand()
- Remove unused meta_client_clock_drift column

fix(migrations): update data_column_sidecar table structure

---

docker-compose.yml

Split Kafka topics into two groups based on message size requirements:
- Large message topics (10MB): blob sidecars, fork choice, blocks, transactions
- Regular topics: standard size for events, attestations, and other data
Added broker configuration to support 10MB message limits.

feat(docker): configure kafka topics with differentiated message size limits

---

deploy/local/docker-compose/vector-kafka-clickhouse-libp2p.yaml
pkg/clmimicry/gossipsub_blob_sidecar.go
pkg/clmimicry/gossipsub_data_column_sidecar.go
pkg/clmimicry/gossipsub_data_column_sidecar_test.go

Adds `block_root` (`body_root`) to both blob and data column sidecar events so downstream consumers can correlate sidecars with their originating beacon block.

feat: add beacon_block_root field to blob and data column sidecars

---

.gitignore
deploy/local/docker-compose/xatu-server-entrypoint.sh
docker-compose.yml
example_server.yaml
get-geo.sh
pkg/server/geoip/geoip.go
pkg/server/geoip/lookup/precision.go
pkg/server/geoip/maxmind/config.go
pkg/server/geoip/maxmind/database/city.go
pkg/server/geoip/maxmind/geonames/config.go
pkg/server/geoip/maxmind/geonames/parser.go
pkg/server/geoip/maxmind/maxmind.go
pkg/server/service/coordinator/client.go
pkg/server/service/event-ingester/auth/groups.go
pkg/server/service/event-ingester/event/beacon/eth/v1/beacon_p2p_attestation.go
pkg/server/service/event-ingester/event/libp2p/trace_connected.go
pkg/server/service/event-ingester/event/libp2p/trace_disconnected.go
pkg/server/service/event-ingester/event/libp2p/trace_synthetic_heartbeat.go
pkg/server/service/event-ingester/event/noderecord/consensus.go
pkg/server/service/event-ingester/event/noderecord/execution.go
pkg/server/service/event-ingester/handler.go

Implement GeoNames integration to provide consistent city/country/continent centroids for IP geolocation. This allows for privacy-preserving geo data storage by using fixed coordinates per location rather than IP-specific ones.
- Add precision levels (Full/City/Country/Continent/None) to geo lookups
- Integrate GeoNames data for city and country centroids
- Add explicit `precision` field to group configuration (no longer inferred)
- Add separate `asn` flag to control ASN data inclusion independently from geo precision
- PrecisionNone allows complete geo privacy by skipping lookups entirely
- Create `get-geo.sh` script to download MaxMind and GeoNames data files
- Support configurable precision based on user privacy settings
- Update Docker setup to mount GeoNames files
- Add example …

feat(geoip): add GeoNames support for consistent geo centroids

---

deploy/local/docker-compose/vector-kafka-clickhouse.yaml

fix(vector-kafka-clickhouse.yaml): use length! to fail fast when kzg_commitments is missing

---

pkg/proto/libp2p/trace.go

tysm sends CustodyGroupCount as uint64 (from `metadata.CustodyGroupCount()` which returns uint64), xatu was expecting uint8 in the type assertion

fix: align custodyGroupCount type assertion with protobuf uint64
