ethpandaops/xatu

go.mod, go.sum
currently fails to build on windows https://github.com/ethpandaops/xatu/actions/runs/3879382840/jobs/6638152032
=> fix(build): windows go-ole fixes

pkg/output/http/exporter.go
=> chore(output): change http exporter to debug log level

.golangci.yml, pkg/discovery/coordinator/client.go, pkg/mimicry/config.go, pkg/mimicry/p2p/execution/execution.go, pkg/output/config.go, pkg/output/http/exporter.go, pkg/output/http/http.go, pkg/output/stdout/exporter.go, pkg/output/stdout/stdout.go, pkg/output/xatu/exporter.go, pkg/output/xatu/xatu.go, pkg/processor/batch.go, pkg/processor/batch_test.go, pkg/processor/metrics.go, pkg/proto/xatu/xatu.go, pkg/sentry/config.go, pkg/sentry/sentry.go, pkg/server/service/coordinator/node/record.go, pkg/server/service/event-ingester/ingester.go
Adds metrics to the processor, along with error logging for each of the sinks
=> feat(processor): Add metrics

pkg/sentry/ethereum/duties.go
=> refactor: Start attestation duties asynchronously

pkg/sentry/ethereum/services/duties.go
Fixes https://github.com/ethpandaops/ethPandaOps/issues/902
=> fix: return error for out of range position in GetValidatorIndex

pkg/cannon/deriver/beacon/eth/v2/deposit.go
=> fix(cannon): Fix calculation of slot in processEpoch

.goreleaser.yaml
=> fix(ci): Remove CGO_ENABLED=0

pkg/output/xatu/config.go, pkg/output/xatu/exporter.go
=> fix: Xatu Keepalive False

go.mod, pkg/sentry/sentry.go
Closes: https://github.com/ethpandaops/xatu/pull/390
=> build(sentry): use yaml.v3

.github/workflows/alpha-releases.yaml, .github/workflows/cannon-smoke-test.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/goreleaser.yaml, .github/workflows/sentry-smoke-test.yaml, .github/workflows/test-build.yaml, .github/workflows/test.yaml
Adding the specific versions as a comment
=> Update github actions dependencies to show full versions in comment

go.mod, go.sum
The hermes library has been updated to the latest version to incorporate subnet configuration functionality.
=> fix(go.mod, go.sum): update hermes

go.mod, go.sum
Bumps `beacon` pkg from `v0.49.0` to `v0.51.0`
=> build: update beacon dep

go.mod, go.sum
Update the ethwallclock dependency to version 0.4.0.
=> build: update ethwallclock dependency to v0.4.0

pkg/sentry/proposed_validator_block.go
The slot is now passed as an argument to `fetchValidatorBlock` and `fetchDecoratedValidatorBlock` instead of being fetched internally based on the wallclock `now` slot. This allows us to configure when we want to request the block in the slot more effectively, and should fix Nimbus blocks.
=> fix(sentry): More control over when a v3 block is requested

go.mod, go.sum
Update the hermes dependency to incorporate recent changes and improvements.
=> build: update hermes dependency to the latest version

go.mod, go.sum
Update the replaced hermes dependency to a newer commit to incorporate recent changes.
=> build: update hermes dependency to a newer commit

example_discovery.yaml, go.mod, go.sum, pkg/discovery/config.go, pkg/discovery/discovery.go, pkg/discovery/p2p/config.go, pkg/discovery/p2p/consensus_crawler.go, pkg/discovery/p2p/status.go
Example config:
> Addition of `beaconNodeUrl`.
> `0xAD532CEB` mainnet
```yaml
p2p:
type: xatu
beaconNodeUrl: http://localhost:5052
config:
address: localhost:8080
tls: false
discV4: false
discV5: true
restart: 2m
networkIds: [1]
forkIdHashes: [0xc376cf8b] # execution layer
forkDigests: [0xAD532CEB] # consensus layer
```
=> refactor(discovery): further implementation

pkg/relaymonitor/ethereum/ethereum.go
```
time="2025-07-10T12:44:09+10:00" level=info msg="Starting beacon..." module=consensus/beacon
time="2025-07-10T12:44:09+10:00" level=error msg="failed to bootstrap node.. will retry in 5s" error="client is not active" module=consensus/beacon
time="2025-07-10T12:44:16+10:00" level=error msg="failed to bootstrap node.. will retry in 10s" error="client is not active" module=consensus/beacon
time="2025-07-10T12:44:26+10:00" level=error msg="failed to bootstrap node.. will retry in 15s" error="client is not active" module=consensus/beacon
time="2025-07-10T12:44:41+10:00" level=error msg="failed to bootstrap node.. will retry in 20s" error="client is not active" module=consensus/beacon
time="2025-07-10T12:45:01+10:00" level=error msg="failed to bootstrap node.. will retry in 25s" …
```
=> fix(relay-monitor): Correctly detect beacon node startup failure

deploy/local/docker-compose/vector-kafka-clickhouse-libp2p.yaml
https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiICByb290RXZlbnRLZXkgPSBzZWFoYXNoKC5kYXRhLnJvb3RfZXZlbnRfaWQpXG5cbiAgIyAtLS0tLSBCcm9rZW4gKGZvciBjb21wYXJpc29uKTpcbiAga2V5LCBlcnIgPSByb290RXZlbnRLZXkgKyBcInJwY19tZXRhX2NvbnRyb2xfaWhhdmVcIiArIHRvX3N0cmluZyguZGF0YS5jb250cm9sX2luZGV4KSArIFwiX1wiICsgdG9fc3RyaW5nKC5kYXRhLm1lc3NhZ2VfaW5kZXgpXG4gIC5icm9rZW4udW5pcXVlX2tleSA9IGtleVxuICAuYnJva2VuLnVuaXF1ZV9rZXlfaGFzaGVkID0gc2VhaGFzaChrZXkpXG5cbiAgIyAtLS0tLS0gRml4ZWQ6XG4gIGtleTEsIGVycjEgPSB0b19zdHJpbmcocm9vdEV2ZW50S2V5KSArIFwiX3JwY19tZXRhX2NvbnRyb2xfaWhhdmVfXCIgKyB0b19zdHJpbmcoLmRhdGEuY29udHJvbF9pbmRleCkgKyBcIl9cIiArIHRvX3N0cmluZyguZGF0YS5tZXNzYWdlX2luZGV4KVxuICAuZml4ZWQudW5pcXVlX2tleSA9IGtleTFcbiAgLmZpeGVkLnVuaXF1ZV9rZXlfaGFzaGVkID0gc2VhaGFzaChrZXkxKVxuXG4gICMgLS0tLS0gRGVidWc6XG4gIC5kZWJ1Zy5ycGNfbWV0YV …
=> fix(vector): improve unique key generation for RPC meta events

go.mod, go.sum
Picking up changes from https://github.com/attestantio/go-eth2-client/pull/250
=> fix: Bump attestant fulu branch

pkg/server/service/event-ingester/event/event.go
Must've been a bad merge on the fulu branch?
=> feat: add handler for beacon eth v1 events data column sidecar

.github/workflows/cannon-smoke-test.yaml
=> ci(cannon-smoke-test): update secret for utility node

pkg/clmimicry/mimicry.go
Bridge Hermes' OpenTelemetry counters to the existing Prometheus registry so both native and OTel metrics are served on /metrics.
=> feat(mimicry.go): wire OpenTelemetry Prometheus exporter for Hermes metrics
